### ISSUE TITLE
feat: add app_names alongside package names in /patches

### ISSUE THREAD

**Issue by preetamdaila** [ReVanced/revanced-api#175] opened 2024-04-13 22:29 UTC
Current /patches have package name in _compatiblePackages_ and app names are not available. 

Few packages have different name from their app names, which is confusing for normal users to find if there is patch available for those apps or not. People know apps by their names not package name. If app names be available we can show app name alongside package name on frontend to make it easy for general users.

**Comment by oSumAtrIX** [comment] 2024-04-14 00:09
Dupe of #161

**Closed by oSumAtrIX** 2024-04-14 00:09 UTC
